---
#
# Description of the helm chart for Ubuntu util pods
#
apiVersion: v2
name: util-ubuntu
description: Deploys ubuntu pods for utility action

type: application
version: 0.2.0
appVersion: "22.04"
