---
#
# The pod
#
apiVersion: apps/v1
  {{ if .Values.daemonset }}
kind: DaemonSet
  {{ else }}
kind: Deployment
  {{ end }}
metadata:
  name: ubuntu-util
spec:
  {{ if not .Values.daemonset }}
  replicas: {{ .Values.replicas }}
  {{ end }}
  selector:
    matchLabels:
      app: ubuntu-util
  template:
    metadata:
      labels:
        app: ubuntu-util
    spec:
{{ if .Values.hostNetworking }}
      hostNetwork: true
{{ end }}
      containers:
        - name: util
          image: {{ .Values.image }}
          resources:
            limits:
              cpu: {{ .Values.limits.cpu }}
              memory: {{ .Values.limits.memory }}
            requests:
              cpu: '100m'
              memory: '128Mi'
